src/Entity/Animals.php
<?php

namespace App\Entity;

use App\Repository\AnimalsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnimalsRepository::class)
 */
class Animals
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $poids;

    /**
     * @ORM\Column(type="boolean")
     */
    private $dangereux;

    /**
     * @ORM\ManyToOne(targetEntity=Famille::class, inversedBy="animaux")
     * @ORM\JoinColumn(nullable=false)
     */
    private $famille;

    /**
     * @ORM\ManyToMany(targetEntity=Continent::class, mappedBy="animaux")
     */
    private $continents;

    public function __construct()
    {
        $this->continents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPoids(): ?int
    {
        return $this->poids;
    }

    public function setPoids(int $poids): self
    {
        $this->poids = $poids;

        return $this;
    }

    public function getDangereux(): ?bool
    {
        return $this->dangereux;
    }

    public function setDangereux(bool $dangereux): self
    {
        $this->dangereux = $dangereux;

        return $this;
    }

    public function getFamille(): ?Famille
    {
        return $this->famille;
    }

    public function setFamille(?Famille $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    /**
     * @return Collection|Continent[]
     */
    public function getContinents(): Collection
    {
        return $this->continents;
    }

    public function addContinent(Continent $continent): self
    {
        if (!$this->continents->contains($continent)) {
            $this->continents[] = $continent;
            $continent->addAnimaux($this);
        }

        return $this;
    }

    public function removeContinent(Continent $continent): self
    {
        if ($this->continents->removeElement($continent)) {
            $continent->removeAnimaux($this);
        }

        return $this;
    }
}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

use App\Entity\Animals;
use App\Repository\AnimalsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AnimalController extends AbstractController
{
    #[Route('/', name: 'animaux')]
    public function index(AnimalsRepository $repository): Response
    {
        $animaux = $repository->findAll();
        return $this->render('animal/index.html.twig',[
            "animaux" =>$animaux
        ]);
    }

    #[Route('/animal/{id}', name: 'afficher_animal')]
    public function afficherAnimal(Animals $animal): Response
    {
        return $this->render('animal/afficherAnimal.html.twig',[
            "animal" => $animal
        ]);
    }
}

templates/animal/afficherAnimal.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <h1>{% block monTitre %}Affichage de l'animal {{ animal.nom }}{% endblock %}</h1>
        </div>
            <div class="row align-items-center">
                <div class="col-3 text-center" ><img class="animal-image" src="{{ asset('images/' ~ animal.image) }}"  alt="animaux"></div>
                <div class="col-9">
                    <div>Description : {{ animal.description }}</div>
                    <div> Poids :  {{ animal.poids }}</div>
                    <div> Dangereux :
                        {% if animal.dangereux %}
                           <span class="badge bg-danger">Oui</span>
                        {%else %}
                            <span class="badge bg-success">Non</span>
                        {% endif %}

                    </div>

                </div>

            </div>


    </div>

{% endblock %}

templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <h1>{% block monTitre %}Voici la liste des animaux{% endblock %}</h1>
        </div>
        {% for animal in animaux %}
            <div class="row align-items-center">
                <div class="col-3 text-center p-2">
                    <img class="animal-image" src="{{ asset('images/' ~ animal.image) }}"  alt="animaux">
                </div>
                <div class="col-9">
                    <h4><a href="{{ path("afficher_animal", {'id' : animal.id}) }}" class="nav-link">{{ animal.nom }}</a></h4>
                    <div> {{ animal.description }}</div>
                    <div>
                        <a class="btn btn-success text-uppercase" href="{{ path("afficher_familles",{'id': animal.famille.id}) }}">
                            {{ animal.famille.libelle }}
                        </a>
                    </div>
                    <div>
                        {% for continent in animal.continents %}
                            <a href class="btn btn-warning">{{ continent.libelle }}</a>
                        {% endfor %}

                    </div>
                </div>

            </div>

        {% endfor %}
    </div>

{% endblock %}